-- ============================================================
--  Projekt Guessr — Mehrspieler-Lobby schema
--  Run ONCE in the Supabase SQL editor (shared project for all
--  three sites — rooms/room_players are NOT prefixed).
--  Idempotent: safe to re-run.
-- ============================================================

-- 1) Extend the shared rooms table for the lobby/N-player model -----
alter table public.rooms add column if not exists host_id          text;
alter table public.rooms add column if not exists status           text default 'lobby';   -- lobby | playing | finished
alter table public.rooms add column if not exists max_players      integer;                -- NULL = unbegrenzt
alter table public.rooms add column if not exists rounds           integer default 5;
alter table public.rooms add column if not exists modifiers        jsonb default '{}'::jsonb; -- {noMove,noLook,timeLimit,speedBonus}
alter table public.rooms add column if not exists round_started_at timestamptz;
alter table public.rooms add column if not exists site             text;                   -- 'ternberg'|'wels'|'scharten' — trennt Räume der drei Seiten

-- 2) One row per player (so concurrent clients never clobber each other) ----
create table if not exists public.room_players (
  id           bigint generated by default as identity primary key,
  room_id      text not null references public.rooms(id) on delete cascade,
  player_id    text not null,
  name         text not null,
  is_host      boolean not null default false,
  ready        boolean not null default false,
  online       boolean not null default true,
  last_seen    timestamptz not null default now(),
  scores       integer[] not null default '{}',
  guess_latlng jsonb,
  kicked       boolean not null default false,
  skip_vote    integer,                 -- Runde, für die dieser Spieler "Überspringen" gewählt hat (NULL = keine Stimme)
  joined_at    timestamptz not null default now()
);
-- skip_vote nachträglich für bestehende Tabellen ergänzen (idempotent)
alter table public.room_players add column if not exists skip_vote integer;
create unique index if not exists room_players_room_player_uniq on public.room_players (room_id, player_id);
create index if not exists room_players_room_idx on public.room_players (room_id);

-- 3) Row Level Security (matches the existing permissive setup) -----
alter table public.room_players enable row level security;
do $mp$
begin
  execute 'drop policy if exists room_players_all on public.room_players;';
  execute 'create policy room_players_all on public.room_players for all to anon, authenticated using (true) with check (true);';
end
$mp$;

grant usage on schema public to anon, authenticated;
grant all on public.room_players to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
