const T = {

  // main
  appName:        'TernberGuessr',
  appTagline:     'wie gut kennst du ternberg?',
  footerMade:     'Website mit Liebe von Fabio erstellt.',

  // account
  authSignIn:     '↪ Anmelden',
  authSignOut:    'Abmelden',
  authLogoutTitle:'Abmelden?',
  authLogoutBody: 'Du wirst von deinem Account abgemeldet.',
  authLogoutYes:  'Abmelden',
  authLogoutNo:   'Abbrechen',

  loginModalTitle:      'Hast du schon einen Account?',
  loginModalHint:       'Melde dich an oder erstelle einen neuen. Damit werden deine Punkte automatisch gespeichert!',
  loginNewAccount:      'Neuer Account',
  loginExistingAccount: 'Einloggen',
  loginNamePlaceholder: 'Dein Name',
  loginPwPlaceholder:   'Passwort',
  loginPwHintNew:       'Erstellt deinen Account. Merke dir das Passwort!',
  loginPwHintExisting:  'Dein bisheriges Passwort.',
  loginSubmitBtn:       'Anmelden',
  loginNameChecking:    'Prüfe…',
  loginNameTaken:       'Vergeben.',
  loginNameAvailable:   'Verfügbar!',
  loginErrorNamePw:     'Bitte Name und Passwort eingeben.',
  loginErrorNameFormat: 'Name: nur Buchstaben, Zahlen, . - _ erlaubt.',
  loginErrorNameTaken:  'Name vergeben.',
  loginErrorNotFound:   'Account nicht gefunden.',
  loginErrorWrongPw:    'Falsches Passwort.',
  loginErrorGeneric:    'Fehler: ',

  // psoelprgoksdofijölg
  menuTitle:        'Spielen',
  menuSubtitle:     'Wähle einen Modus',
  menuSoloTitle:    'Einzelspieler',
  menuSoloSub:      '5 Runden. Weißt du wo das Bild ist?',
  menuSoloCta:      'Starten →',
  menuDailyTitle:   'Tägliche Challenge',
  menuDailySub:     'Ein Spot, jeden Tag neu.',
  menuDailyCta:     'Ansehen →',
  menuVsTitle:      '1v1',
  menuVsSub:        'Wer ist der wahre Ternberger?',
  menuVsCta:        'Starten →',
  menuSurvivalTitle:'Hitzewelle',
  menuSurvivalSub:  '12 Runden. Mindestpunktzahl steigt.',
  menuSurvivalCta:  'Durchhalten →',
  menuBack:         '← Zurück',

  // daily
  dailyKicker:        'Tägliche Challenge',
  dailyTitle:         'Ein Spot.\nJeden Tag neu.',
  dailyDesc:          'Jeden Tag kommt ein neuer Spot der gleich für alle ist.\nDu hast nur einen Versuch.',
  dailyNextIn:        'Nächster Spot in',
  dailyPlayBtn:       'Spielen',
  dailyAlreadyPlayed: 'Heute schon gespielt',
  dailyBoardTitle:    'Heutiges Leaderboard',
  dailyChampionsTitle:'🏆 Champions von gestern',
  dailyNoEntries:     'Heute noch keine Einträge.',
  dailyLoadError:     'Fehler beim Laden.',

  //spiel 
  gameMapClick:    'Karte anklicken',
  gameGuessBtn:    'Raten →',
  gameExpandMap:   '⤢ Vergrößern',
  gameDragHint:    'ziehen zum Umsehen · scrollen zum Zoomen',
  gameBackBtn:     '← Menü',
  gameBackConfirm: 'Zum Hauptmenü zurückgehen? Dein Fortschritt geht verloren.',

  // ergbnus
  resultLabelDist:    'Entfernung',
  resultLabelPts:     'Punkte',
  resultLabelTotal:   'Gesamt',
  resultNextRound:    'Nächste Runde → ',
  resultWaitOpponent: 'Warte auf ',

  // hitzwelkle
  survivalThresholdHud:   '🔥 Min. ',
  survivalThresholdUnit:  ' Pkt. nötig',
  survivalScoreLabel:     'Deine Punkte',
  survivalPassedVerdict:  'Schwelle geschafft!',
  survivalFailedVerdict:  'Ausgeschieden.',
  survivalFailTitle:      'Ausgeschieden!',
  survivalRoundLabel:     'Runde',
  survivalThresholdLabel: 'Zielpunkte',

  // hallo
  finalTitleSolo:     'Spiel beendet',
  finalTitleVs:       'Spiel beendet',
  finalTitleDaily:    'Tägliche Challenge beendet',
  finalTitleSurvival: '🔥 Hitzewelle bestanden!',
  finalSubDaily:      '/ 5 000 Punkte',
  finalSubUnit:       ' Punkte',
  finalSaveBtn:       'Punkte eintragen',
  finalShareBtn:      '📤 Teilen',
  finalHeatmapBtn:    '🌡 Heatmap',
  finalPlayAgainBtn:  'Nochmal',
  finalHomeBtn:       'Hauptmenü',
  finalNewHighscore:  '🏆 NEUER HIGHSCORE!',

  //vs
  vsModalTitle:         'Gegeneinander',
  vsCreateTitle:        'Raum erstellen',
  vsCreateHint:         'Erstelle einen Raum und teile den Code.',
  vsJoinTitle:          'Raum beitreten',
  vsJoinHint:           'Gib den Code von deinem Gegner ein.',
  vsJoinCodePlaceholder:'Raumcode (z.B. ABC123)',
  vsCreatedTitle:       'Raum erstellt',
  vsShareHint:          'Teile diesen Code mit deinem Gegner:',
  vsWaitingText:        'Warte auf Gegner…',
  vsQrHint:             'Scannen um schnell beizutreten!',
  vsYouWin:             'DU HAST GEWONNEN! 🏆',
  vsTheyWin:            ' gewinnt.',
  vsDraw:               'Unentschieden.',
  vsRoomFull:           'Raum ist bereits voll.',
  vsRoomNotFound:       'Raum nicht gefunden.',
  vsJoinError:          'Name und Code eingeben.',
  vsCreateError:        'Fehler beim Erstellen: ',
  vsJoinBtnLabel:       'Beitreten',
  vsCreateBtnLabel:     'Erstellen',
  vsCancelBtn:          'Abbrechen',

  // leaderboard
  lbTitle:           'Bestenliste',
  lbTabAll:          'Alle',
  lbTabMonth:        'Monat',
  lbTabWeek:         'Woche',
  lbSortPts:         '◆ Punkte',
  lbSortDate:        '📅 Datum',
  lbLoading:         'Lade…',
  lbEmpty:           'Noch keine Einträge.',
  lbClose:           'Schließen',
  lbClickForProfile: 'Profil ansehen',

  // profil
  profileStat_games:     'Spiele',
  profileStat_best:      'Bestes Spiel',
  profileStat_avg:       'Ø Punkte',
  profileStat_streak:    'Streak 🔥',
  profileStat_dailies:   'Dailies gespielt',
  profileBackBtn:        '← Zurück',
  profileSince:          'Dabei seit ',
  profileLoading:        'Lade...',
  profileError:          'Fehler beim Laden.',
  profileNoScores:       'Noch keine Spiele.',
  profileNoAchievements: 'Noch keine Erfolge.',

  // achievements
  achievements: {
    first_game:   { icon: '🎮', title: 'Erster Schritt',   desc: 'Erstes Spiel gespielt' },
    first_perfect:{ icon: '💎', title: 'Perfektion',        desc: '5000 Punkte in einer Runde' },
    streak_3:     { icon: '🔥', title: 'Am Laufen',         desc: '3 Tage in Folge gespielt' },
    streak_7:     { icon: '🔥🔥',title: 'Auf Kurs',         desc: '7 Tage in Folge gespielt' },
    streak_30:    { icon: '👑', title: 'Aktiver Ternberger',  desc: '30 Tage in Folge gespielt' },
    score_10k:    { icon: '⭐', title: 'Über 10.000',       desc: '10.000+ Punkte in einem Spiel' },
    score_20k:    { icon: '🌟', title: 'Über 20.000',       desc: '20.000+ Punkte in einem Spiel' },
    score_25k:    { icon: '🏆', title: 'Wahrer Ternberger', desc: '25.000 Punkte. Perfektes Spiel' },
    survival_win: { icon: '🌋', title: 'Überlebt!',         desc: 'Alle 12 Hitzewelle Runden bestanden' },
    daily_10:     { icon: '📅', title: 'Stammgast',         desc: '10 Daily Challenges gespielt' },
  },

  // schwierigkeit
  diffOverlayTitle: 'Wie schwer war dieser Spot?',
  diffSkipBtn:      'Überspringen',
  // 1-5
  diffLabels:       ['', 'Sehr einfach', 'Einfach', 'Normal', 'Schwer', 'Sehr schwer'],
  diffDisplayPrefix:'Schwierigkeit: ',
  diffCountSingle:  ' Bewertung',
  diffCountMultiple:' Bewertungen',

  chartRoundLabel: 'R',

  heatmapTitle:         'Wo haben alle geraten?',
  heatmapHintLoading:   'Lade…',
  heatmapNoData:        'Noch keine Daten.',
  heatmapError:         'Fehler beim Laden.',
  heatmapClose:         'Schließen',
  heatmapTipsSuffix:    ' Tipps von heute',
  heatmapTipsSuffixSolo:' Tipps für diesen Spot',

  saveTitle:          'Punkte eintragen',
  saveQuestion:       'Hast du schon einen Account?',
  saveNewAccount:     'Nein',
  saveExistAccount:   'Ja',
  saveNamePlaceholder:'Dein Name',
  savePwPlaceholder:  'Passwort',
  saveSaveBtn:        'Speichern',
  saveCancelBtn:      'Abbrechen',
  saveSuccess:        '✓ Eingetragen!',

  verdictPools: [
    [4950, ['Wohnst du da oder was?', 'WOW!', 'Schon narrisch', 'Fotografisches Gedächtnis.', 'Unglaublich.', 'Du WOHNST dort, oder?']],
    [4700, ['Der war sehr gut.', 'Fast perfekt.', 'Sehr stark, wirklich.', 'Du kennst Ternberg gut!', 'Beeindruckend.', 'Den hast!']],
    [4300, ['Sehr solid.', 'Gute Runde!', 'Nicht schlecht, nicht schlecht.', 'Die Gegend hast du gefunden.', 'So geht das!', 'Sauber getroffen.']],
    [3600, ['Ganz ordentlich.', 'Solide Leistung.', 'Wars nicht doch das andere Haus?', 'Nicht perfekt, aber gut.', 'Passt eh.', 'War ok.']],
    [2800, ['Mittelfeld. Geht so.', 'Könnte besser sein.', 'Du bist irgendwie in der Nähe.', 'War nicht optimal, aber ok.', 'Na ja. Hast du geschlafen?']],
    [2000, ['Du warst in der Nähe. Naja.', 'Hmm. Nächstes Mal besser.', 'Das war mutig.', 'Schaffst mehr, ich glaubs.', 'Ternberg ist groß, aber nicht SO groß.']],
    [1200, ['Hast du Ternberg schonmal auf der Karte gesehen?', 'Irgendwo in Österreich immerhin.', 'Wennst meinst.', 'Wenigstens im richtigen Land.', 'Zumindest europäischer Kontinent.']],
    [600,  ['War das Absicht?', 'Mutig geraten.', 'Du hast einfach irgendwo geklickt.', 'Ternberg ist in Österreich. Nur zur Info.', 'Fast null, aber das schaffst du auch noch.']],
    [150,  ['Ich frage mich ob du überhaupt hingeschaut hast.', 'Wennst meinst.', 'Fast kein Punkt.', 'Ich bin nicht wütend, nur enttäuscht.', 'Ich bin nicht wütend, nur enttäuscht.']],
    [0,    ['Ternberg ist in Österreich, nicht in Asien.', 'Na.', 'Der wars wirklich ned.', 'Selbst mit verbundenen Augen wärst du näher dran.', 'Ich bin sprachlos.']]
  ],
  // streak
  streakDaySingle:  'Tag gespielt!',
  streakDayMultiple:'Tage in Folge gespielt!',

  // changelog
  changelogEyebrow:  'TernberGuessr News',
  changelogTitle:    'TernberGuessr',
  changelogSubtitle: 'Alle Änderungen, Ankündigungen & Neuerungen',
  changelogEmpty:    'Noch keine Updates eingetragen.',
  changelogLoading:  'Lade…',
  changelogNewEntry: '✏️ Neuer Eintrag',
  changelogBtnLabel: '📰 Was ist neu?',

};
